// Generated by gencpp from file message_learning/myMsgType.msg
// DO NOT EDIT!


#ifndef MESSAGE_LEARNING_MESSAGE_MYMSGTYPE_H
#define MESSAGE_LEARNING_MESSAGE_MYMSGTYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace message_learning
{
template <class ContainerAllocator>
struct myMsgType_
{
  typedef myMsgType_<ContainerAllocator> Type;

  myMsgType_()
    : id(0)
    , name(0)
    , roll(0)  {
    }
  myMsgType_(const ContainerAllocator& _alloc)
    : id(0)
    , name(0)
    , roll(0)  {
  (void)_alloc;
    }



   typedef int64_t _id_type;
  _id_type id;

   typedef int64_t _name_type;
  _name_type name;

   typedef int64_t _roll_type;
  _roll_type roll;





  typedef boost::shared_ptr< ::message_learning::myMsgType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::message_learning::myMsgType_<ContainerAllocator> const> ConstPtr;

}; // struct myMsgType_

typedef ::message_learning::myMsgType_<std::allocator<void> > myMsgType;

typedef boost::shared_ptr< ::message_learning::myMsgType > myMsgTypePtr;
typedef boost::shared_ptr< ::message_learning::myMsgType const> myMsgTypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::message_learning::myMsgType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::message_learning::myMsgType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::message_learning::myMsgType_<ContainerAllocator1> & lhs, const ::message_learning::myMsgType_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.name == rhs.name &&
    lhs.roll == rhs.roll;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::message_learning::myMsgType_<ContainerAllocator1> & lhs, const ::message_learning::myMsgType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace message_learning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::message_learning::myMsgType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message_learning::myMsgType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_learning::myMsgType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_learning::myMsgType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_learning::myMsgType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_learning::myMsgType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::message_learning::myMsgType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99a91f415d35171986878c5468ff93a0";
  }

  static const char* value(const ::message_learning::myMsgType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99a91f415d351719ULL;
  static const uint64_t static_value2 = 0x86878c5468ff93a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::message_learning::myMsgType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message_learning/myMsgType";
  }

  static const char* value(const ::message_learning::myMsgType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::message_learning::myMsgType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 id\n"
"int64 name\n"
"int64 roll\n"
;
  }

  static const char* value(const ::message_learning::myMsgType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::message_learning::myMsgType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.roll);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myMsgType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::message_learning::myMsgType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::message_learning::myMsgType_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<int64_t>::stream(s, indent + "  ", v.name);
    s << indent << "roll: ";
    Printer<int64_t>::stream(s, indent + "  ", v.roll);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_LEARNING_MESSAGE_MYMSGTYPE_H
