// Generated by gencpp from file trail/SquareServiceRequest.msg
// DO NOT EDIT!


#ifndef TRAIL_MESSAGE_SQUARESERVICEREQUEST_H
#define TRAIL_MESSAGE_SQUARESERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trail
{
template <class ContainerAllocator>
struct SquareServiceRequest_
{
  typedef SquareServiceRequest_<ContainerAllocator> Type;

  SquareServiceRequest_()
    : a(0)  {
    }
  SquareServiceRequest_(const ContainerAllocator& _alloc)
    : a(0)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::trail::SquareServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trail::SquareServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SquareServiceRequest_

typedef ::trail::SquareServiceRequest_<std::allocator<void> > SquareServiceRequest;

typedef boost::shared_ptr< ::trail::SquareServiceRequest > SquareServiceRequestPtr;
typedef boost::shared_ptr< ::trail::SquareServiceRequest const> SquareServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trail::SquareServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trail::SquareServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::trail::SquareServiceRequest_<ContainerAllocator1> & lhs, const ::trail::SquareServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::trail::SquareServiceRequest_<ContainerAllocator1> & lhs, const ::trail::SquareServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace trail

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::trail::SquareServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trail::SquareServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trail::SquareServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trail::SquareServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trail::SquareServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trail::SquareServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trail::SquareServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c9fb1a886e81e3162a5c87bf55c072b";
  }

  static const char* value(const ::trail::SquareServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c9fb1a886e81e31ULL;
  static const uint64_t static_value2 = 0x62a5c87bf55c072bULL;
};

template<class ContainerAllocator>
struct DataType< ::trail::SquareServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trail/SquareServiceRequest";
  }

  static const char* value(const ::trail::SquareServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trail::SquareServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 a\n"
;
  }

  static const char* value(const ::trail::SquareServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trail::SquareServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SquareServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trail::SquareServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trail::SquareServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAIL_MESSAGE_SQUARESERVICEREQUEST_H
