// Generated by gencpp from file trail/SquareService.msg
// DO NOT EDIT!


#ifndef TRAIL_MESSAGE_SQUARESERVICE_H
#define TRAIL_MESSAGE_SQUARESERVICE_H

#include <ros/service_traits.h>


#include <trail/SquareServiceRequest.h>
#include <trail/SquareServiceResponse.h>


namespace trail
{

struct SquareService
{

typedef SquareServiceRequest Request;
typedef SquareServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SquareService
} // namespace trail


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::trail::SquareService > {
  static const char* value()
  {
    return "2449c4788bda2a0af56de75bb4fc040b";
  }

  static const char* value(const ::trail::SquareService&) { return value(); }
};

template<>
struct DataType< ::trail::SquareService > {
  static const char* value()
  {
    return "trail/SquareService";
  }

  static const char* value(const ::trail::SquareService&) { return value(); }
};


// service_traits::MD5Sum< ::trail::SquareServiceRequest> should match
// service_traits::MD5Sum< ::trail::SquareService >
template<>
struct MD5Sum< ::trail::SquareServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::trail::SquareService >::value();
  }
  static const char* value(const ::trail::SquareServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::trail::SquareServiceRequest> should match
// service_traits::DataType< ::trail::SquareService >
template<>
struct DataType< ::trail::SquareServiceRequest>
{
  static const char* value()
  {
    return DataType< ::trail::SquareService >::value();
  }
  static const char* value(const ::trail::SquareServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::trail::SquareServiceResponse> should match
// service_traits::MD5Sum< ::trail::SquareService >
template<>
struct MD5Sum< ::trail::SquareServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::trail::SquareService >::value();
  }
  static const char* value(const ::trail::SquareServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::trail::SquareServiceResponse> should match
// service_traits::DataType< ::trail::SquareService >
template<>
struct DataType< ::trail::SquareServiceResponse>
{
  static const char* value()
  {
    return DataType< ::trail::SquareService >::value();
  }
  static const char* value(const ::trail::SquareServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAIL_MESSAGE_SQUARESERVICE_H
