// Generated by gencpp from file services_learning/SquareService.msg
// DO NOT EDIT!


#ifndef SERVICES_LEARNING_MESSAGE_SQUARESERVICE_H
#define SERVICES_LEARNING_MESSAGE_SQUARESERVICE_H

#include <ros/service_traits.h>


#include <services_learning/SquareServiceRequest.h>
#include <services_learning/SquareServiceResponse.h>


namespace services_learning
{

struct SquareService
{

typedef SquareServiceRequest Request;
typedef SquareServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SquareService
} // namespace services_learning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::services_learning::SquareService > {
  static const char* value()
  {
    return "2449c4788bda2a0af56de75bb4fc040b";
  }

  static const char* value(const ::services_learning::SquareService&) { return value(); }
};

template<>
struct DataType< ::services_learning::SquareService > {
  static const char* value()
  {
    return "services_learning/SquareService";
  }

  static const char* value(const ::services_learning::SquareService&) { return value(); }
};


// service_traits::MD5Sum< ::services_learning::SquareServiceRequest> should match
// service_traits::MD5Sum< ::services_learning::SquareService >
template<>
struct MD5Sum< ::services_learning::SquareServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::services_learning::SquareService >::value();
  }
  static const char* value(const ::services_learning::SquareServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::services_learning::SquareServiceRequest> should match
// service_traits::DataType< ::services_learning::SquareService >
template<>
struct DataType< ::services_learning::SquareServiceRequest>
{
  static const char* value()
  {
    return DataType< ::services_learning::SquareService >::value();
  }
  static const char* value(const ::services_learning::SquareServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::services_learning::SquareServiceResponse> should match
// service_traits::MD5Sum< ::services_learning::SquareService >
template<>
struct MD5Sum< ::services_learning::SquareServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::services_learning::SquareService >::value();
  }
  static const char* value(const ::services_learning::SquareServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::services_learning::SquareServiceResponse> should match
// service_traits::DataType< ::services_learning::SquareService >
template<>
struct DataType< ::services_learning::SquareServiceResponse>
{
  static const char* value()
  {
    return DataType< ::services_learning::SquareService >::value();
  }
  static const char* value(const ::services_learning::SquareServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICES_LEARNING_MESSAGE_SQUARESERVICE_H
