// Generated by gencpp from file services_learning/SquareServiceResponse.msg
// DO NOT EDIT!


#ifndef SERVICES_LEARNING_MESSAGE_SQUARESERVICERESPONSE_H
#define SERVICES_LEARNING_MESSAGE_SQUARESERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace services_learning
{
template <class ContainerAllocator>
struct SquareServiceResponse_
{
  typedef SquareServiceResponse_<ContainerAllocator> Type;

  SquareServiceResponse_()
    : square(0)  {
    }
  SquareServiceResponse_(const ContainerAllocator& _alloc)
    : square(0)  {
  (void)_alloc;
    }



   typedef int32_t _square_type;
  _square_type square;





  typedef boost::shared_ptr< ::services_learning::SquareServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::services_learning::SquareServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SquareServiceResponse_

typedef ::services_learning::SquareServiceResponse_<std::allocator<void> > SquareServiceResponse;

typedef boost::shared_ptr< ::services_learning::SquareServiceResponse > SquareServiceResponsePtr;
typedef boost::shared_ptr< ::services_learning::SquareServiceResponse const> SquareServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::services_learning::SquareServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::services_learning::SquareServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::services_learning::SquareServiceResponse_<ContainerAllocator1> & lhs, const ::services_learning::SquareServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.square == rhs.square;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::services_learning::SquareServiceResponse_<ContainerAllocator1> & lhs, const ::services_learning::SquareServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace services_learning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::services_learning::SquareServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::services_learning::SquareServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::services_learning::SquareServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::services_learning::SquareServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::services_learning::SquareServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::services_learning::SquareServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::services_learning::SquareServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d99d7e4ed611bb1ba8a036b291e1ffb";
  }

  static const char* value(const ::services_learning::SquareServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d99d7e4ed611bb1ULL;
  static const uint64_t static_value2 = 0xba8a036b291e1ffbULL;
};

template<class ContainerAllocator>
struct DataType< ::services_learning::SquareServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "services_learning/SquareServiceResponse";
  }

  static const char* value(const ::services_learning::SquareServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::services_learning::SquareServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 square\n"
"\n"
;
  }

  static const char* value(const ::services_learning::SquareServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::services_learning::SquareServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.square);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SquareServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::services_learning::SquareServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::services_learning::SquareServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "square: ";
    Printer<int32_t>::stream(s, indent + "  ", v.square);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICES_LEARNING_MESSAGE_SQUARESERVICERESPONSE_H
